### ISSUE TITLE
Why nextTick is used when add/dell to room?

### ISSUE THREAD

**Issue by fourpixels** [socketio/socket.io-adapter#33]
I've seen this multiple times and I can't figure this out. Why when socket is added/deleted from room the callback is called with `process.nextTick`? 

As there is **no** option to return an error, nor there is a real synchronous function - is there any reason why this is done? Sometimes it's pretty handy if synchronous.

**Comment by artofspeed** [comment]
when u scale to multiple servers, it'll not be synchronous, forcing async standardize your development + give a chance for other code to execute

**Comment by darrachequesne** [comment]
That's a good question actually. It seems to be implemented that way from the beginning (https://github.com/socketio/socket.io/commit/67f7d5749ba63eaf8f0d14fdfc8a30c5d77da76b). Maybe it was related to other adapter implementations?

Anyway, the callbacks were removed in https://github.com/socketio/socket.io-adapter/commit/53ed3f4099c073546c66d911a95171adcefc524c, so I think we can close this.
