### ISSUE TITLE
Adapter.prototype.broadcast performance

### ISSUE THREAD

**Issue by jorgemsrs** [socketio/socket.io-adapter#38]
Hello.

`Adapter.prototype.broadcast` always encodes the packet even if there are no rooms or connected clients.

In practice this causes namespaces with no connected clients but with high traffic to affect the latency for namespaces that have connected clients because the CPU is crammed, encoding data that will never reach a client.

I can help looking at this and submitting a merge request but first I want to hear from you if you see value in optimising this behaviour before I start.

What do you think?

**Comment by darrachequesne** [comment]
@jorgemsrs PR is welcome!

**Comment by darrachequesne** [comment]
Please reopen if needed.
