### ISSUE TITLE
Socket.io with cluster

### ISSUE THREAD

**Issue by AeonRush** [socketio/socket.io-adapter#40]
Hi
[Here a Gist](https://gist.github.com/AeonRush/ee01e3fcdd336a70c62409f1b0f55394) with sample.
When I run it I have a multiply `time` event on client. I tried a `cluster` and a [`sticky-session`](https://github.com/indutny/sticky-session) but result the same.
Maybe I doing something wrong?

**Comment by darrachequesne** [comment]
Hi! That kind of questions belongs to Stackoverflow. Also, please try to avoid opening multiple issues for the same matter (https://github.com/socketio/socket.io-redis/issues/144, https://github.com/indutny/sticky-session/issues/53). Thanks!

Closed as duplicate.
