### ISSUE TITLE
rooms and sids are protected

### ISSUE THREAD

**Issue by ejose19** [socketio/socket.io-adapter#63]
Refers to https://github.com/socketio/socket.io/issues/3697

Is there any particular reason you made those protected? If it's to not allow modifications from the outside, shouldn't we provide ```getRooms``` and ```getSids``` to act as getters? I can work on a PR if this is the approved solution.

**Comment by darrachequesne** [comment]
Let's make them public then: https://github.com/socketio/socket.io-adapter/commit/313c5a9fb60d913cd3a866001d67516399d8ee2f

Included in `socket.io-adapter@2.1.0` & `socket.io@3.1.0`.
