### ISSUE TITLE
Promisify socketRooms

### ISSUE THREAD

**Issue by DavraYoung** [socketio/socket.io-adapter#67]
Let's make socketRooms return promise.

Sometimes it's usefull to know what rooms the specific socket is in.  In single node, the Adapter.socketRooms(socketId) function works as intended.

However, with multiple socket.io servers connected through socket.io-redis adapter, it is impossible to know what rooms the socket is in, if the socket is from different node.

Making Adapter.socketRooms function to return promise will allow other adapters to implement logic of getting socket rooms even if the socket is not stored in current node.

**Comment by darrachequesne** [comment]
Hi! I was thinking about adding this feature with: https://github.com/socketio/socket.io-adapter/commit/1c9827ec1136e24094295907efaf4d4e6c2fef2f

Syntax (open to discussion):

```js
const sockets = await io.in("room3").fetchSockets();
for (const socket of sockets) {
  console.log(socket.rooms); // along with id & handshake
}
```

What do you think?

**Comment by DavraYoung** [comment]
Hi, sorry I didn't answer for a long time, this is somewhat similar to [Adapter.sockets()](https://github.com/socketio/socket.io-adapter/blob/c679e62236f093548ee4ac991cb849d9d8474947/lib/index.ts#L148),
But that won't solve my problem: how can I fetch rooms for specific socket in redis adapter?

The problem is in [Adapter.socketRooms](https://github.com/socketio/socket.io-adapter/blob/c679e62236f093548ee4ac991cb849d9d8474947/lib/index.ts#L163) function - it is not returning Promise.

Finding rooms of specific socket requires asynchronous function calls, and because [Adapter.socketRooms](https://github.com/socketio/socket.io-adapter/blob/c679e62236f093548ee4ac991cb849d9d8474947/lib/index.ts#L163) does not return promise, its impossible to override this method for redis adapter. So, it simply returns undefined, if I call it with sid, which does not belong to this node.

**Comment by DavraYoung** [comment]
Thanks, the functinality that I was trying to achieve was covered in recent commit [here](https://github.com/socketio/socket.io-adapter/commit/1c9827ec1136e24094295907efaf4d4e6c2fef2f#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567R200)

**Comment by darrachequesne** [comment]
Good news, thanks a lot for the feedback :pray:
