### ISSUE TITLE
socket.io-adapter block emit calls

### ISSUE THREAD

**Issue by Hovhanns97** [socketio/socket.io-adapter#71]
In my application, I have used a socket.io and also an adapter for it. Now when I try to send a response from the server to the frontend with socket.to(id).emit("message", message), it throws this error

![unknown](https://user-images.githubusercontent.com/84914696/119829172-05a2cc00-bf0c-11eb-9b6a-3729d895e0d8.png)

It starts working again after I comment on the code that configures the adapter.

`io.adapter(require("socket.io-redis")({host: "localhost", port: 6379}))`

But it's not a good solution, because I need to use the adapter for my application. How can I fix this problem in another way?

**Comment by darrachequesne** [comment]
It sounds like a compatibility issue. Which version of `socket.io-redis` / `socket.io` are you using?

Related: https://github.com/socketio/socket.io-redis-adapter/issues/402

**Comment by Hovhanns97** [comment]
I am using these versions.
"socket.io": "4.0.1",
"socket.io-client": "^4.1.2",
"socket.io-redis": "^6.1.0",

**Comment by darrachequesne** [comment]
This should be fixed with `socket.io-redis@6.1.1`, could you please try to run `npm update`?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
