### ISSUE TITLE
There seems to be a problem with the computeExceptSids method called in the apply method.

### ISSUE THREAD

**Issue by zishang520** [socketio/socket.io-adapter#82]
BroadcastOptions.except is of type `Set<SocketId>` but computeExceptSids requires `Set<Room>`:
https://github.com/socketio/socket.io-adapter/blob/b92d65cf9c6124930fac78349e2a0b847fe19f16/lib/index.ts#L288

BroadcastOptions.except:
https://github.com/socketio/socket.io-adapter/blob/b92d65cf9c6124930fac78349e2a0b847fe19f16/lib/index.ts#L19

computeExceptSids:
https://github.com/socketio/socket.io-adapter/blob/b92d65cf9c6124930fac78349e2a0b847fe19f16/lib/index.ts#L313

**Comment by darrachequesne** [comment]
Good catch, thanks! This should be fixed by https://github.com/socketio/socket.io-adapter/commit/3410584a9322dd07145e3dc60b892c17d46c3aeb.
