### ISSUE TITLE
error TS1005: ',' expected V 2.5.3

### ISSUE THREAD

**Issue by caburet** [socketio/socket.io-adapter#86]
Hi, good evening.
I'm using socket.io with an **old version** of TSC 4.3.5 and a new version of socket.io-adapter V 2.5.3. With the new version i had a problem when i run TSC command. Close this issue if you think TSC is too old. Thanks

`[Container] 2024/02/21 17:59:00.205028 Running command npm run build

api_node@1.0.0 build
npx tsc

node_modules/socket.io-adapter/dist/cluster-adapter.d.ts(1,24): error TS1005: ',' expected.
node_modules/socket.io-adapter/dist/cluster-adapter.d.ts(1,45): error TS1005: ',' expected.
node_modules/socket.io-adapter/dist/cluster-adapter.d.ts(1,68): error TS1005: ',' expected.

[Container] 2024/02/21 17:59:21.459878 Command did not exit successfully npm run build exit status 2`

**Comment by darrachequesne** [comment]
Sorry for that! This should be fixed by https://github.com/socketio/socket.io-adapter/commit/ca397f3afe06ed9390db52b70a506a9721e091d8, included in [`2.5.4`](https://github.com/socketio/socket.io-adapter/releases/tag/2.5.4).

**Comment by caburet** [comment]
Thanks!
